version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py collectstatic --noinput &&
               gunicorn --bind 0.0.0.0:8000 Learny.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=Learny.settings
      - POSTGRES_DB=learny_db
      - POSTGRES_USER=learny_user
      - POSTGRES_PASSWORD=learny_password
      - DATABASE_URL=postgresql://learny_user:learny_password@db:5432/learny_db
    depends_on:
      - db
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=learny_db
      - POSTGRES_USER=learny_user
      - POSTGRES_PASSWORD=learny_password

volumes:
  postgres_data:
  static_volume:
  media_volume:
