# Generated by Django 5.0 on 2025-01-12 07:39

import tutorials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a thumbnail image (16:9 ratio recommended)', null=True, upload_to='tutorials/thumbnails/', validators=[tutorials.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_file',
            field=models.FileField(upload_to='tutorials/videos/', validators=[tutorials.models.validate_video_extension]),
        ),
    ]
