# Generated by Django 5.0 on 2025-01-12 08:18

import tutorials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a section thumbnail (16:9 ratio recommended)', null=True, upload_to='sections/thumbnails/', validators=[tutorials.models.validate_image_extension]),
        ),
    ]
